"""empty message

Revision ID: 1b2cd184f6bf
Revises: None
Create Date: 2016-09-12 12:22:06.752099

"""

# revision identifiers, used by Alembic.
revision = '1b2cd184f6bf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'user_id')
    ### end Alembic commands ###
